category_list=[
    {'title': 'General', 'sub': ['Basic']},
    {'title': 'Software Engineering', 'sub': ['Web Developer', 'UX-UI', 'Tester', 'Front-end Developer', 'Back-end Developer']},
    {'title': 'Sales', 'sub': ['Sales Representative', 'Sales Manager', 'Salesman', 'Salesforce Administrator', 'Sales Director', 'Account executive', 'Real Estate']},
    {'title': 'Marketing/PR', 'sub': ['Public Relations', 'Marketing Manager', 'Marketing Assistant', 'Event Coordinator', 'Digital Marketing', 'Content Manager', 'Brand Ambassador Manager', 'Advertising Manager']},
    {'title': 'Management', 'sub': ['Strategic Manager', 'Risk Manager', 'Project Manager', 'Managar', 'Executive']},
    {'title': 'Legal', 'sub': ['Legal Secretary', 'Administrative Assistant', 'Lawyer', 'Counselor', 'Attorney']},
    {'title': 'IT', 'sub': ['Programmer', 'Network Engineer', 'IT Support', 'Information Security Analyst', 'Game Designer', 'Databse Administator']},
    {'title': 'Human Resources', 'sub': ['Talent Acquisition Specialist', 'Recruiter', 'Human Resources Assistant', 'H R Manager']},
    {'title': 'Healthcare', 'sub': ['Veterinary', 'Pharmacy Thechnician', 'Nurse', 'Mental Health Therapist', 'Medical Doctor', 'Medical Assistant', 'Dentist']},
    {'title': 'Engineering', 'sub': ['Quality Engineer', 'QA Engineer', 'Production Manager', 'Mechanical Engineer', 'Electrical Engineer', 'Civil Engineer', 'Chemical Engineer', 'CAD Designer', 'Aerospace Engineer']},
    {'title': 'Customer Service', 'sub': ['Sales Associate', 'Customer Support', 'Client Relationship Manager', 'Call Center']},
    {'title': 'Business', 'sub': ['Startup', 'Investor', 'Enterpreneur', 'Consulting', 'Business Development', 'Account Manager']},
    {'title': 'Automotive', 'sub': ['Technician', 'Worker', 'Production', 'Mechanic', 'Car Dealer']},
    {'title': 'Art/Design', 'sub': ['Video Editor', 'Product Designer', 'Photographer', 'Interior Designer', 'Graphic Desiner', 'Copywriter', 'Art Director']},
    {'title': 'Administative', 'sub': ['Personal Assistant', 'Office Staff', 'Front Desk Receptionist', 'Facilities Manager', 'Administration']},
    {'title': 'Accounting/ Finance', 'sub': ['Tax Services', 'Investment Advisor', 'Insurance Agent', 'Finance Analyst', 'Bookkeeper', 'Auditor', 'Accountant']},
]