
quotes=[
    {"1":'"Success is not final, failure is not fatal: It is the courage to continue that counts." - Winston Churchill'},
    {"1":'"The only way to do great work is to love what you do." - Steve Jobs'},
    {"1":'"Your time is limited, don\'t waste it living someone else\'s life." - Steve Jobs'},
    {"1":'"Dream big and dare to fail." - Norman Vaughan'},
    {"1":'"The journey of a thousand miles begins with one step." - Lao Tzu'},
    {"2":"Start your day with gratitude. Write down three things you're thankful for."},
    {"2":"Stay hydrated! Drink at least 8 glasses of water every day."},
    {"2":"Take a 5-minute break every hour to stretch and relax."},
    {"2":"Set achievable goals for the day. Break them into smaller tasks for a sense of accomplishment."},
    {"2":"Practice deep breathing exercises to reduce stress and improve focus."},
    {"2":"Read for at least 15 minutes every day. It's a great way to expand your knowledge."},
    {"2":"Connect with a friend or loved one today. Social connections are vital for your well-being."},
    {"2":"Prioritize self-care. Dedicate time to do something you love every day."},
    {"2":"Learn something new daily. Whether it's a new word or a new skill, keep your mind active."},
    {"2":"Reflect on your day before bed. What went well, and what can you improve tomorrow?"},
    {"1":'"The future belongs to those who believe in the beauty of their dreams." - Eleanor Roosevelt'},
    {"1":'"Don\'t watch the clock; do what it does. Keep going." - Sam Levenson'},
    {"1":'"Success is walking from failure to failure with no loss of enthusiasm." - Winston Churchill'},
    {"1":'"Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work." - Steve Jobs'},
    {"2":"Capture Attention: In your video profile, start with a compelling introduction to grab the viewer's interest."},
    {"2":"Tell Your Story: Use the video to convey your career journey, showcasing your passion and achievements."},
    {"2":"Be Concise: Keep your video profile under 60 seconds. Focus on key highlights."},
    {"2":"Highlight Skills: Mention skills that make you an ideal candidate for the job."},
    {"2":"Practice Confidence: Speak clearly, maintain eye contact, and exude confidence in your video."},
    {"2":"Showcase Personality: Let your personality shine through, making you more memorable."},
    {"2":"Stay Professional: Dress appropriately and choose a clean, well-lit backdrop."},
    {"2":"Demonstrate Enthusiasm: Express your genuine interest in the role and company."},
    {"2":"Align with Resume: Ensure your video complements your written resume, enhancing your application."},
    {"2":"Edit Thoughtfully: Edit your video for brevity and clarity. Every second counts."},
    {"2":"Practice, Practice, Practice: Rehearse your video introduction until you're comfortable and confident."},
    {"2":"Tell a Story: Narrate a brief story or accomplishment that illustrates your skills and character."},
    {"2":"Speak to the Role: Tailor your video message to match the specific job you're applying for."},
    {"2":"Engage with Energy: Enthusiasm is contagious. Show your passion for your field."},
    {"2":"Check Audio and Video: Ensure your video and audio quality are top-notch. No distractions!"},
    {"2":"Focus on Value: Explain how your skills and experience can benefit the employer."},
    {"2":"Watch Your Body Language: Maintain good posture and use natural gestures."},
    {"2":"Be Authentic: Be yourself in your video. Authenticity is appreciated by employers."},
    {"2":"Seek Feedback: Share your video with a trusted friend or mentor for constructive feedback."},
    {"2":"Revisit and Revise: Don't hesitate to re-record your video profile to make it even better."},
]
